[package]
name = "net-proto-api"
version = "0.1.0"
edition = "2021"

[dependencies]
ion-rs = "0.18.1"
ion-schema = "0.7.0"

[features]
ion-text = []
ion-binary = []
ion-schema-validation = []

default = ["ion-text"]