# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "edge"

[dependencies]
rand = "0.8.5"
pcap = "0.9.2"
serde = { version = "1.0.140", features = ["derive"] }
bincode = "1.3.3"
zmq = "0.9.2"
websocket = "0.26.5"
simple-websockets = "0.1.4"
message-io = "0.14.6"
tungstenite = "0.17.3"
scoped_threadpool = "0.1.9"
tokio = "1.20.1"
futures = "0.3.21"
bytes = "1.2.1"
httparse = "1.7.1"
base64 = "0.13.0"
sha-1 = "0.10.0"