[workspace]

members = [ "core",
    "net-inserter",
    "net-migrator",
    "net-reporter"
]

[workspace.dependencies]

log = "0.4.17"
log4rs = "1.2.0"
threadpool = "1.8.1"

directories = "5.0.0"
config = "0.13.3"
serde = { version = "1.0.156", features = ["derive"] }
toml = "0.7.3"
