[package]
name = "net-timescale-api"
version = "0.1.2"
edition = "2021"


[dependencies]
net-proto-api.workspace = true
net-transport.workspace = true
net-config.workspace = true

ion-rs = "0.18.1"

[features]
ion-text = []
ion-binary = []

default = ["ion-text"]