[connection_url]
url = "postgres://postgres:PsWDgxZb@localhost:5433"

[max_connection_size]
size = "10"

[server]
host_name = "net-reporter"
port = "5454"
addr = "127.0.0.1:5454"

[fusion_auth_server_addres]
addr = "http://localhost:9011"

[fusion_auth_api_key]
key = "gw_awXW6h11DZ7ncwyim23-wQ76IAsM947L5p9Wb7yYOR0Erh_yQKCD4"